baseURL = 'https://Chathura1990.github.io/quantized-quality-blog/'
languageCode = 'en-us'
title = 'Quantized Quality'
theme = 'PaperMod'

[params]
  author = "Chathura S.R"
  enableGitInfo = false
  ShowPostThumbnails = true

[params.profileMode]
  enabled = false